[theme]
base = "dark"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
primaryColor = "#F7931A"
textColor = "#E6EDF3"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
